/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intranet;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author 2class-004
 */
public class Intra extends javax.swing.JFrame {

    /**
     * Creates new form Intra
     */
    public Intra(){
        initComponents();
        lbEmpno.setText("1000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pTop = new javax.swing.JPanel();
        lbMypage = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        pLeft = new javax.swing.JPanel();
        lbNotice = new javax.swing.JLabel();
        lbBoard = new javax.swing.JLabel();
        lbMeetroom = new javax.swing.JLabel();
        lbAdmin = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pBoard = new javax.swing.JPanel();
        bd_lbHeader = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        bd_spList = new javax.swing.JScrollPane();
        tbBoard = new javax.swing.JTable();
        btWrite = new javax.swing.JButton();
        tfWrite = new javax.swing.JTextField();
        lbWrite = new javax.swing.JLabel();
        lbEmpno = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 620));

        pTop.setBackground(new java.awt.Color(121, 176, 215));

        lbMypage.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbMypage.setForeground(new java.awt.Color(255, 255, 255));
        lbMypage.setText("마이페이지");

        lbMsg.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(255, 255, 255));
        lbMsg.setText("쪽지함");

        lbLogout.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setText("로그아웃");

        lbLogo.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMypage)
                .addGap(18, 18, 18)
                .addComponent(lbMsg)
                .addGap(18, 18, 18)
                .addComponent(lbLogout)
                .addGap(26, 26, 26))
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTopLayout.createSequentialGroup()
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTopLayout.createSequentialGroup()
                        .addGroup(pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMypage)
                            .addComponent(lbMsg)
                            .addComponent(lbLogout))
                        .addGap(30, 30, 30))))
        );

        pLeft.setBackground(new java.awt.Color(204, 204, 204));

        lbNotice.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbNotice.setText("◎ 공지사항");
        lbNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbNoticeMousePressed(evt);
            }
        });

        lbBoard.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbBoard.setText("◎ 한 줄 게시판");

        lbMeetroom.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbMeetroom.setText("◎ 회의실 예약");

        lbAdmin.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbAdmin.setForeground(new java.awt.Color(102, 102, 102));
        lbAdmin.setText("관리자 모드");

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdmin)
                    .addComponent(lbMeetroom)
                    .addComponent(lbBoard)
                    .addComponent(lbNotice))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbNotice)
                .addGap(18, 18, 18)
                .addComponent(lbBoard)
                .addGap(18, 18, 18)
                .addComponent(lbMeetroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdmin)
                .addGap(30, 30, 30))
        );

        pCenter.setLayout(new java.awt.CardLayout());

        pBoard.setBackground(new java.awt.Color(255, 255, 255));

        bd_lbHeader.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        bd_lbHeader.setText("::: 한 줄 게시판 :::");

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "글번호", "작성자", "내  용" }));
        cbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchActionPerformed(evt);
            }
        });

        btSearch.setText("검색");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        tbBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "글번호", "작성자", "내   용", "작성일"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bd_spList.setViewportView(tbBoard);

        btWrite.setText("글쓰기");
        btWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
            		btWriteActionPerformed(evt);					
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });

        lbWrite.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        lbWrite.setText("작성자 :");

        btDelete.setText("삭제");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBoardLayout = new javax.swing.GroupLayout(pBoard);
        pBoard.setLayout(pBoardLayout);
        pBoardLayout.setHorizontalGroup(
            pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBoardLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBoardLayout.createSequentialGroup()
                        .addComponent(bd_lbHeader)
                        .addGap(709, 709, 709))
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pBoardLayout.createSequentialGroup()
                                .addComponent(btDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSearch))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pBoardLayout.createSequentialGroup()
                                .addComponent(lbWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEmpno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btWrite))
                            .addComponent(bd_spList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        pBoardLayout.setVerticalGroup(
            pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBoardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(bd_lbHeader)
                .addGap(18, 18, 18)
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btWrite)
                    .addComponent(tfWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bd_spList, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pCenter.add(pBoard, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(pCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pTop, javax.swing.GroupLayout.PREFERRED_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>                        

    BoardDAO bDAO= new BoardDAO();
    private void lbNoticeMousePressed(java.awt.event.MouseEvent evt) {                                      

    }                                     

    private void cbSearchActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btWriteActionPerformed(java.awt.event.ActionEvent evt) throws Exception
    {                                        
        
    	String empno=lbEmpno.getText();
    	String msg= tfWrite.getText();
    	ArrayList<BoardVO> al= new ArrayList<>();
		//무결성
		if(msg.trim().isEmpty())
		{
			showMessage("내용을 입력하세요");
			tfWrite.requestFocus();
			return;
		}
		
		//vo객체 생성후 세팅하기
		BoardVO bVO= new BoardVO();
		bVO.setName(empno);
		bVO.setMsg(msg);
		
		String regCheck=(bDAO.writeBoard(bVO)>0)? "성공":"실패";
		
		showMessage(regCheck);
    	
    }                                       

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    	
        
    }                                        

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    public void showMessage(String msg)
    {
    	JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bd_lbHeader;
    private javax.swing.JScrollPane bd_spList;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btWrite;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbBoard;
    private javax.swing.JLabel lbEmpno;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMeetroom;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbMypage;
    private javax.swing.JLabel lbNotice;
    private javax.swing.JLabel lbWrite;
    private javax.swing.JPanel pBoard;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pTop;
    private javax.swing.JTable tbBoard;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfWrite;
    // End of variables declaration                   
}
