/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intranet;

/**
 *
 * @author 2class-004
 */
public class Msg extends javax.swing.JFrame {

    /**
     * Creates new form Msg
     */
    public Msg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMsg = new javax.swing.JPanel();
        pMsgList = new javax.swing.JPanel();
        mm_lbHeader = new javax.swing.JLabel();
        mm_tpList = new javax.swing.JTabbedPane();
        spRcvList = new javax.swing.JScrollPane();
        tabRcvList = new javax.swing.JTable();
        spSendList = new javax.swing.JScrollPane();
        tabSendList = new javax.swing.JTable();
        mm_btWrite = new javax.swing.JButton();
        mm_btDel = new javax.swing.JButton();
        pMsgRead = new javax.swing.JPanel();
        mr_lbHeader = new javax.swing.JLabel();
        mr_lbTitle = new javax.swing.JLabel();
        mr_tfTitle = new javax.swing.JTextField();
        mr_lbSendid = new javax.swing.JLabel();
        mr_tfSendid = new javax.swing.JTextField();
        mr_spText = new javax.swing.JScrollPane();
        mr_taText = new javax.swing.JTextArea();
        mr_btBacktoList = new javax.swing.JButton();
        mr_btDel = new javax.swing.JButton();
        pMsgWrite = new javax.swing.JPanel();
        mw_lbHeader = new javax.swing.JLabel();
        mw_lbTitle = new javax.swing.JLabel();
        mw_tfTitle = new javax.swing.JTextField();
        mw_spText = new javax.swing.JScrollPane();
        mw_taText = new javax.swing.JTextArea();
        mw_btSend = new javax.swing.JButton();
        mw_btCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMsg.setLayout(new java.awt.CardLayout());

        mm_lbHeader.setText("내 쪽지함");

        tabRcvList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spRcvList.setViewportView(tabRcvList);

        mm_tpList.addTab("받은 쪽지함", spRcvList);

        tabSendList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spSendList.setViewportView(tabSendList);

        mm_tpList.addTab("보낸 쪽지함", spSendList);

        mm_btWrite.setText("쪽지 보내기");
        mm_btWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mm_btWriteActionPerformed(evt);
            }
        });

        mm_btDel.setText("삭제");

        javax.swing.GroupLayout pMsgListLayout = new javax.swing.GroupLayout(pMsgList);
        pMsgList.setLayout(pMsgListLayout);
        pMsgListLayout.setHorizontalGroup(
            pMsgListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgListLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pMsgListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pMsgListLayout.createSequentialGroup()
                        .addComponent(mm_btWrite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mm_btDel))
                    .addGroup(pMsgListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mm_tpList, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mm_lbHeader)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMsgListLayout.setVerticalGroup(
            pMsgListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgListLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mm_lbHeader)
                .addGap(18, 18, 18)
                .addComponent(mm_tpList, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMsgListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mm_btDel)
                    .addComponent(mm_btWrite))
                .addContainerGap())
        );

        pMsg.add(pMsgList, "card2");

        mr_lbHeader.setText("내 쪽지함");

        mr_lbTitle.setText("제목");

        mr_lbSendid.setText("보낸 사람");

        mr_taText.setColumns(20);
        mr_taText.setRows(5);
        mr_spText.setViewportView(mr_taText);

        mr_btBacktoList.setText("글목록");
        mr_btBacktoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_btBacktoListActionPerformed(evt);
            }
        });

        mr_btDel.setText("삭제");

        javax.swing.GroupLayout pMsgReadLayout = new javax.swing.GroupLayout(pMsgRead);
        pMsgRead.setLayout(pMsgReadLayout);
        pMsgReadLayout.setHorizontalGroup(
            pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgReadLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pMsgReadLayout.createSequentialGroup()
                        .addComponent(mr_btBacktoList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mr_btDel))
                    .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mr_spText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mr_lbHeader, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pMsgReadLayout.createSequentialGroup()
                            .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mr_lbSendid)
                                .addComponent(mr_lbTitle))
                            .addGap(18, 18, 18)
                            .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mr_tfTitle)
                                .addComponent(mr_tfSendid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pMsgReadLayout.setVerticalGroup(
            pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgReadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mr_lbHeader)
                .addGap(26, 26, 26)
                .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mr_lbTitle)
                    .addComponent(mr_tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mr_lbSendid)
                    .addComponent(mr_tfSendid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mr_spText, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pMsgReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mr_btDel)
                    .addComponent(mr_btBacktoList))
                .addContainerGap())
        );

        pMsg.add(pMsgRead, "card2");

        mw_lbHeader.setText("내 쪽지함");

        mw_lbTitle.setText("제목");

        mw_taText.setColumns(20);
        mw_taText.setRows(5);
        mw_spText.setViewportView(mw_taText);

        mw_btSend.setText("보내기");
        mw_btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mw_btSendActionPerformed(evt);
            }
        });

        mw_btCancle.setText("취소");

        javax.swing.GroupLayout pMsgWriteLayout = new javax.swing.GroupLayout(pMsgWrite);
        pMsgWrite.setLayout(pMsgWriteLayout);
        pMsgWriteLayout.setHorizontalGroup(
            pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgWriteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pMsgWriteLayout.createSequentialGroup()
                        .addComponent(mw_btSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mw_btCancle))
                    .addGroup(pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mw_spText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mw_lbHeader, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pMsgWriteLayout.createSequentialGroup()
                            .addComponent(mw_lbTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mw_tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pMsgWriteLayout.setVerticalGroup(
            pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMsgWriteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mw_lbHeader)
                .addGap(26, 26, 26)
                .addGroup(pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mw_lbTitle)
                    .addComponent(mw_tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mw_spText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pMsgWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mw_btCancle)
                    .addComponent(mw_btSend))
                .addContainerGap())
        );

        pMsg.add(pMsgWrite, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mr_btBacktoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_btBacktoListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mr_btBacktoListActionPerformed

    private void mw_btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mw_btSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mw_btSendActionPerformed

    private void mm_btWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mm_btWriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mm_btWriteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Msg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mm_btDel;
    private javax.swing.JButton mm_btWrite;
    private javax.swing.JLabel mm_lbHeader;
    private javax.swing.JTabbedPane mm_tpList;
    private javax.swing.JButton mr_btBacktoList;
    private javax.swing.JButton mr_btDel;
    private javax.swing.JLabel mr_lbHeader;
    private javax.swing.JLabel mr_lbSendid;
    private javax.swing.JLabel mr_lbTitle;
    private javax.swing.JScrollPane mr_spText;
    private javax.swing.JTextArea mr_taText;
    private javax.swing.JTextField mr_tfSendid;
    private javax.swing.JTextField mr_tfTitle;
    private javax.swing.JButton mw_btCancle;
    private javax.swing.JButton mw_btSend;
    private javax.swing.JLabel mw_lbHeader;
    private javax.swing.JLabel mw_lbTitle;
    private javax.swing.JScrollPane mw_spText;
    private javax.swing.JTextArea mw_taText;
    private javax.swing.JTextField mw_tfTitle;
    private javax.swing.JPanel pMsg;
    private javax.swing.JPanel pMsgList;
    private javax.swing.JPanel pMsgRead;
    private javax.swing.JPanel pMsgWrite;
    private javax.swing.JScrollPane spRcvList;
    private javax.swing.JScrollPane spSendList;
    private javax.swing.JTable tabRcvList;
    private javax.swing.JTable tabSendList;
    // End of variables declaration//GEN-END:variables
}
